### ISSUE TITLE
NaNs in the end of time series after OutliersTransform

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna-ts#127]
### 🐛 Bug Report

In case, where the dataset contains outliers in the end of some time series(not all), they are replaced with NaNs by the `OutliersTransform` and time series stop being ending in the same timestamp. This cause raising errors in the subsequent transforms.

### Expected behavior

Perform subsequent transforms without raising errors 

### Code
```
import pandas as pd
from etna.datasets.tsdataset import TSDataset
from etna.transforms import DensityOutliersTransform, TimeSeriesImputerTransform

classic_df = pd.read_csv("examples/data/example_dataset.csv")
df = TSDataset.to_dataset(classic_df)
ts = TSDataset(df, freq="D")

params = {"window_size":18,
          "distance_coef":1,
          "n_neighbors":4}
outliers_remover = DensityOutliersTransform(in_column="target",**params)
outliers_imputer = TimeSeriesImputerTransform(in_column="target",strategy="running_mean",window=30)
ts.fit_transform([outliers_remover])
ts.fit_transform([outliers_imputer])

```

### Checklist

- [X] Bug appears at the latest library version
- [X] Bug description added
- [X] Steps to reproduce added
- [X] Expected behavior added

**Comment by martins0n** [comment]
This is expected behaviour -- we call `self._check_endings()` at the beginning of `fit_transform`. 
Outliers remover may make some timeseries shorter, that's why next call of `fit_transform` will rise Exception.

As a workaround you could deepcopy `ts` and call `ts1.fit_transform([outliers_remover])`, `ts2.fit_transform([outliers_remover, outliers_imputer])` via independent tsdatasets.
